### ISSUE TITLE
Adding Dirichlet prior for Ordinal Regression case study

### ISSUE THREAD

**Issue by svilupp** [pyro-ppl/numpyro#1129]
I'd like to contribute an implementation of a more principled prior based on [Ordinal Regression Case Study from M.Betancourt (2019)](https://betanalpha.github.io/assets/case_studies/ordinal_regression.html) (in particular section 2.2). It requires adding a Simplex2Ordered Transform.

Branch location: https://github.com/svilupp/numpyro/tree/ordinal-regr-prior

Changes have been made in the following files (so far):
- distributions/transforms.py - adding the necessary transform
- docs/source/distributions.rst - adding the reference to be displayed in the docs
- notebooks/source/ordinal_regression.ipynb - showcasing how to use it (model4)

I have a few **questions**:
- Am I right to assume that log_abs_det_jacobian() method of Transforms Class is defined as additive in the *transformed space* (ie, log_abs_det_jacobian+log_transformed_density = log_base_density). I have noticed that TransformedDistribution deducts the value from the prob density of the base distribution + I have confirmed empirically. 
For that reason, I have *flipped the sign* compared to the log_abs_det_jacobian in [1]
- I haven't noticed any transform-specific tests (only the class itself). Have I missed it?
- Is the verbosity of the `model4` in Ordinal Regression example appropriate?
- Is there any other file that should be changed?
- All tests pass, until doctest where I get: 
```
Warning, treated as error:
/home/ec2-user/SageMaker/Other/Contrib/numpyro/docs/source/tutorials/bayesian_hierarchical_linear_regression.ipynb:7:Unexpected indentation.
``` 
I haven't made any changes to this file. I have seen this issue before with docstrings missing new lines and I can see a cell, which could be problematic (download URL for the dataset). However, changing it to one long line has no impact on the error. Has anyone encountered this error as well?

***
**TODOs**:

- [x] ensure transform call() and inverse() can handle batch dimensions (currently, it works on vector--> vector basis)
- [x] ensure log_abs_det of the transform can handle batch dimensions 

***
PS: I think there might be some breaking changes in the latest version of JAX, as I had to install jax==0.2.13 jaxlib==0.1.65 otherwise tests would not pass (failing test was hmm_enum.py and some simple array slicing, so the changes seem to be around handling ellipsis) 

***
UPDATE: 
- transform should now fully support batch dimensions

**Comment by fehiepsi** [comment]
This is awesome! Waiting for your PR, @svilupp!

> log_abs_det_jacobian+log_transformed_density = log_base_density

Yes, this is right if `log_abs_det_jacobian` is of the transform from base_domain -> transformed_domain.

> failing test was hmm_enum.py and some simple array slicing

> transform-specific tests

I think you can add one [here](https://github.com/pyro-ppl/numpyro/blob/9da69d2653a2dee77487e613046a7904c99fd29e/test/test_distributions.py#L1657)

> Is the verbosity of the model4 in Ordinal Regression example appropriate?

I think you can make a new section for it. In addition, you can do `print_summary(exclude_deterministic=False)` to also print the property of `y`. Note that using `reparam` is unnecessary. It is helpful to record the probabilities (the base value) in the trace though.

> Is there any other file that should be changed?

Could you submit a PR so I can comment? 

> doctest where I get:
Warning, treated as error:

I think you can skip it. You can test for new features with
```
pytest ... -k some_pattern_to_filter_the_new_tests
```

> breaking changes in the latest version of JAX

Currently, CI passes. Could you submit the PR so we can see what's failing?

**Comment by svilupp** [comment]
Thank you, Fehiepsi. 
I've opened the [PR](https://github.com/pyro-ppl/numpyro/pull/1130); I didn't want to open it until I pass all tests & checks.

I'll add the print summary later today. 
Noted on the `reparam` - I find it quite helpful to see the base probabilities because the Dirichlet prior can be a bit opaque, but I agree that the calibration of the concentration param. should be part of prior checks.

Re. failing tests for hmm_enum.py with the latest JAX - I have resolved by downgrading to jax==0.2.13 jaxlib==0.1.65; if you're not having any issues then it was just a result of some dependency problem in my previous environment.

***
TODOs:

- [ ] update NB - print summary with deterministic sites
- [ ] update tests - add test to the test suite `test_bijective_transforms`

**Comment by svilupp** [comment]
I've updated the case study notebook as suggested, however, I'm not sure about the test.

I've added the transform to the param. decorator of `test_bijective_transforms`, however, it tests several cases, which the transform cannot pass, eg, batch shape = () - for that reason, I've added marks=xFail, however, that devalues the test for all other cases. 
The obvious solution would be to add a `skipif` condition, however, I don't think it can be linked to the value of another parameter unless it's somehow implemented inside of the function.

My rationale for why batch_shape=() cannot pass, is that then it triggers jax.jacobian(), which would automatically produce a non-square matrix. It's because `simplex --> ordered` reduces event_shape by 1, but the original custom Jacobian also includes one more variable encoding the summation constraint for the simplex to sum up to 1 - jax. Jacobian cannot know that.

Would you have any suggestions on how to resolve it without impacting the other tests? 
(I suspect we won't to avoid duplication of the function with different parameters)

**Comment by fehiepsi** [comment]
Hi @svilupp, I just follow up in the PR. It is easier to comment there. :)

**Comment by fehiepsi** [comment]
Thanks, @svilupp!
