### ISSUE TITLE
Use classes as interface for SVI and MCMC

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#285]
**Tasks** (to be expanded): 
 - [x] Create `SVI` class; mark existing `svi` interface as deprecated.
 - [x] Create `MCMC` class; mark existing `mcmc` interface as deprecated.
 - [x] Create `Optim` class to wrap over jax optimizers.

**Motivation:**

Related: #274 

As I am looking at the codebase with fresh eyes, it seems to me that we have to write a lot of boiler-plate code in NumPyro due to the functional style of the API. 

e.g. for SVI:

```python
    opt_init, opt_update, opt_params = optimizers.adam(0.01)
    rng_guide, rng_init, rng_train = random.split(random.PRNGKey(1), 3)
    svi_init, svi_update, _ = svi(model, guide, elbo, opt_init, opt_update, opt_params)
    opt_state, get_params = svi_init(rng_init, model_args=(data,), guide_args=(data,))

    def body_fn(i, val):
        opt_state_, rng_ = val
        loss, opt_state_, rng_ = svi_update(i, rng_, opt_state_, model_args=(data,), guide_args=(data,))
        return opt_state_, rng_

    opt_state, _ = fori_loop(0, 1000, body_fn, (opt_state, rng_train))
    print(get_params(opt_state))
```

While this can be simplified somewhat with #274, in an ideal world, this should be as simple and easy to remember as:

```python
svi = svi(model, guide, optim, loss)
svi.run(1000, rng)  # also provide svi.update for users to loop
print(svi.get_params())
```

**Alternative:** Another option would be to provide another functional API like `svi_run(..)` in the same spirit as `mcmc`. The disadvantage of that is that it caters to a very simple use case with a single return type. If the users want to get the optimizer `get_state` and the `constrain_fn` and also the final `parameters`, it becomes cumbersome. We'll have to offer two options (like with `mcmc`) - a simple interface which returns the learned parameters, or else write all the boiler plate code and get access to all the intermediate variables.

I am trying to think through the benefits / drawbacks of using classes vs. our current functional API:

**Using classes:**
Benefits:
 - We can have a minimal API that offers the same functionality with much less boilerplate code, since we don't have to cycle arguments back and forth, and can abstract whatever functional logic we need to deal with the RNG or optimizer inside the class.
 - Being able to introspect classes and individual methods e.g. `isinstance(inference_algorithm, 'svi')`, or `dir(svi)` or having jupyter notebook autocomplete class methods. This also allows sphinx to generate documentation without any hacks. Better IDE support.

Drawbacks:
 - Creating many stateful variables and making it harder to JIT certain methods. From what I can see (e.g. with autoguides), this risk can probably be easily managed by avoiding setting state outside of `__init__`. 

**Functional API**
Benefits:
 - This style seems in line with other JAX modules like `optimizers` and `stax`. These modules are still relatively quite simple as compared to our inference algorithms.

Drawbacks:
 - Boiler plate code - I mostly end up copying from an existing example.
 - Harder to introspect by IDEs, sphinx and jupyter notebook, since the function signature of internal functions can't be introspected by just importing the module. 

@fehiepsi - What are your thoughts? I might be missing some other important details.

**Comment by fehiepsi** [comment]
I like to use classes at those places from early time!! Not just SVI, I think it is better to make `mcmc` a class. The function `mcmc` requires me to change the source code every time to get some results for debugging (e.g. to get num_steps from multi-chains). With classes, it will be more flexible for us to add methods for different purposes.

I think if we use classes for inference APIs `MCMC`, `SVI`, it would be great.

**Comment by neerajprad** [comment]
> I think if we use classes for inference APIs MCMC, SVI, it would be great.

Okay, great to know. Let us target having a nice simple interface for both of these for the next release!
