### ISSUE TITLE
Checklist for first release

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/numpyro#29]
- [x] Add sphinx to generate documentation.
 - [x] Add docstring to existing modules.
   - [x] Revisit #60 @fehiepsi
 - [x] Update README - what is currently supported, some small examples, and future plans.
   - [ ] Add pypi version badge to readme
   - [x] Add readthedocs badge to readme
 - [x] Include examples in unit-test to ensure compatibility with release.
 - [x] A couple of good notebooks with explanations (not for benchmarking).
    - [x] local global trend. @fehiepsi 
    - [x] bayesian regression. @neerajprad  
    - [x] bayesian NNs. @martinjankowiak who has volunteered to contribute a Bayesian NN tutorial! Not a release blocker though, we can publish it whenever it is ready. 
 - [x] Clean up minor API issues - #144
 - [x] Register docs on readthedocs (or publish on github.io or somewhere public)
    https://numpyro.readthedocs.io/en/latest/distributions.html

Already Done:
 - [x] A few starter issues for external contributors.
 - More interesting examples:
    - [x] SVI - maybe a VAE or SS-VAE example with MNIST.
    - [x] HMC - baseball, hierarchical modeling, bayesian regression.
 - [x] Better coverage for popular distributions - #1 
 - [x] Working HMC, NUTS - doesn't have to be a fully optimized implementation.
 - [x] Benchmarking HMC, NUTS vis-a-vis Pyro, Stan, PyMC3

**Comment by jpchen** [comment]
>More interesting examples

i have a gmm example (forked from the pyro ex) as soon as we have a categorical [edit: i see there's now a multinomial, which i can probably use

**Comment by neerajprad** [comment]
@fehiepsi - After discussing with @fritzo, I think it will be a good idea to move this to pyro-ppl, and develop in public. We should definitely look to address the issues above, and have an initial release at that point. What do you think?

**Comment by fehiepsi** [comment]
@jpchen If you need Dirichlet distribution, please let me know, I will implement it first. :)

**Comment by neerajprad** [comment]
> i have a gmm example (forked from the pyro ex) as soon as we have a categorical 

That's great! I think you should be able to use the multinomial directly, but let me know if you get into any issues.

**Comment by fehiepsi** [comment]
@neerajprad Sure, let's go for it!

**Comment by fritzo** [comment]
Thanks @neerajprad, you could even rename this issue to "Checklist before initial release". Now that we're part of Linux Foundation, I feel like development should be public whenever possible.

**Comment by fehiepsi** [comment]
@neerajprad Nice updates for tasks! ;)

**Comment by fehiepsi** [comment]
> A couple of good notebooks with explanations (not for benchmarking).

@neerajprad Which ones you have in mind? I think that it might be good to have one for bayesian regression (based on the similar one in Pyro) and one for local global trend (an excellent application). :)

**Comment by neerajprad** [comment]
>  I think that it might be good to have one for bayesian regression (based on the similar one in Pyro) and one for local global trend (an excellent application). :)

Let us do it - I could take up the bayesian regression tutorial notebook.

**Comment by fritzo** [comment]
I've added a couple bullets for documentation. It would be nice to publish documentation and maybe tutorials (readthedocs for docs and maybe num.pyro.ai for tutorials? @jpchen how much effort would that be?)

**Comment by neerajprad** [comment]
Thanks, @fritzo! @jpchen has set up readthedocs at https://numpyro.readthedocs.io/en/latest/. Tutorials would be nice to have too, right now I have just linked to the jupyter notebooks on github in readme. @jpchen - let us know how much work that is.

**Comment by jpchen** [comment]
sorry my notifications for this project is misconfigured.

yes i will build the tutorials and push them to the website tonight. id like to move the docs to the pyro.ai domain but that will take a while since it needs to go through multiple approvals internally.
