### ISSUE TITLE
Construct a contrib.forecasting module

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#540]
Follow up https://github.com/pyro-ppl/pyro/issues/2311, it would be great to have a `contrib` module in NumPyro for forecasting. I expected some differences

- Use NUTS instead of SVI and target a single time series, instead of a hierarchical time series like in Pyro. This is not a good approach for problems with a bunch of "hierarchical" time series. Even in that case, with the inference results of some "important" time series, we can get some insight into the data and modeling, hence improving Pyro models.
- Play around Holt-Winters models instead of Kalman filter. I think it would be great if we can match the functionality of [Rlgt](https://cran.r-project.org/web/packages/Rlgt/vignettes/GT_models.html). This is convenient because we already have constructed some models in that package here.

### Tasks

- [x] Sketch an interface, especially focusing on forecasting. It is best to mimic (but simplify) the Pyro interface.
- [x] Add hyperparameters to control modeling details (e.g. multiplicative vs additive, seasonal, local trend, global trend,...) and parameter priors.
- [x] Consider to incorporate `covariates` (maybe through a regression component?).
- [x] Vectorize over seasonality window (as @neerajprad did in [this workshop tutorial](https://github.com/pyro-ppl/sandbox/blob/master/2019-08-time-series/part_ii_inference.ipynb))

I would favor the approach "get it done then refactoring later" like how we developed the functional mcmc then refactoring into MCMC. :smile_cat:

**Comment by fritzo** [comment]
@slaweku what model class would you recommend? Are there any areas where you think NumPyro's fast HMC or neural nets could outperform competing univariate forecasting tools?

**Comment by slaweks17** [comment]
Sure. A typical univariate tool will fit a model per series, thus losing opportunities from cross-learning. Also. when there are meaningful regressors, available in past and for future (like holidays, calendar features) or limited future covered by prediction horizon (like user attributes, promotions) NNs and generally ML algorithms should do better.
