### ISSUE TITLE
Checklist for 0.5 release

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#881]
- [x] Double check that the new documentation page is generated correctly
- [x] Quickly test for Python 3.9
    - tested rethinking-numpyro on python 3.9
- [x] Pin jax=0.2.8, jaxlib=0.1.59
    - [x] Blocked by https://github.com/google/jax/issues/5445, which causes errors on my GPU. **Edit:** solved by installing `jaxlib==0.1.59+cuda110`
- [x] Check that no performance regression, as in jaxlib 0.1.57
- [ ] Make sure that funsor functionalities are synced with the latest funsor release
    - funsor master is required for `_PREV` stuff in scan
- [x] Run isort
- [x] Run update_headers
- [x] Close all [0.5-marked issues](https://github.com/pyro-ppl/numpyro/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5)
- [x] Test statistical rethinking codes
- [x] Collect release notes
