### ISSUE TITLE
Stan like constraints

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#906]
Move the issue https://github.com/pyro-ppl/pyro/issues/2756 to here because the problem has been resolved there. Currently, NumPyro don't those constraints
- [x] #910 sphere - probably this is the only continuous constraint so far that does not have a bijective transform. We might need to raise errors if users use `sphere` in ImproperUniform distribution.
- [x] #913 positive_ordered_vector
- [x] #913 rename `InvCholeskyTransform` to `CholeskyTransform` and `CorrMatrixCholeskyTransform`

**Comment by fritzo** [comment]
I'm working on `sphere` (with `ProjectedNormal` and `ProjectedNormalReparam`)

**Comment by fehiepsi** [comment]
All missing constraints have been implemented. Thanks for addressing this issue, @fritzo!
