### ISSUE TITLE
Check list for 0.6 release

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/numpyro#935]
- [x] (optional) Progress bar for parallel chain #900
- [x] Add some docs for covtype and expose that example to gallery #927 
- [x] Using softplus transform for scale parameters in autoguides #855
- ~[ ] (optional) Finish the embarrassingly parallel tutorial #277~
- [ ] Merge MixedHMC PR #826
- ~[ ] (optional) Add a wrapper for Nested Sampling #807 Probably add some simple-to-implement `cdf` methods (e.g. Uniform.cdf?)~
- [x] Deprecate TruncatedNormal/TruncatedCauchy in favor of more flexible TruncatedDistribution...
- [x] Switch Uniform back to the original Uniform implementation, rather than a TransformedDistribution implementation. Transformed implementation is unnecessary now because we have dropped dynamic support (in favor of the more flexible reparam API)
- [x] Fix some legacy docs in `potential_energy` and `DiscreteHMCGibbs`
- ~[ ] Target jax 0.2.10 and jaxlib 0.1.62?~
- [x] Port `obs_mask` from Pyro https://github.com/pyro-ppl/pyro/pull/2772? then ~update Imputing tutorials~
- [x] Port handler `get_mask` from https://github.com/pyro-ppl/pyro/pull/2751/files and optimize NeuTra, HMCECS, autoguide,...
